name: Deploy Site no GitHub Pages

on:
    workflow_dispatch:
    push:
      paths:
        - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy  GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: src
          publish_branch: gh-pages